# Generated by Django 5.0.6 on 2024-05-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uID', models.AutoField(primary_key=True, serialize=False)),
                ('block_id', models.IntegerField(blank=True, null=True)),
                ('hood_id', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('profile', models.TextField()),
                ('photo', models.CharField(max_length=100)),
                ('home_longitude', models.FloatField(blank=True, null=True)),
                ('home_latitude', models.FloatField(blank=True, null=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
