# Generated by Django 5.0.6 on 2024-05-16 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('text_body', models.TextField()),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('thread_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('thread_id', models.AutoField(primary_key=True, serialize=False)),
                ('initial_message_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uID', models.AutoField(primary_key=True, serialize=False)),
                ('block_id', models.IntegerField(blank=True, null=True)),
                ('hood_id', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('profile', models.TextField()),
                ('photo', models.CharField(max_length=100)),
                ('home_longitude', models.FloatField(blank=True, null=True)),
                ('home_latitude', models.FloatField(blank=True, null=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('recipient_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
                ('message_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyDiscord.message')),
                ('uID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyDiscord.user')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='MyDiscord.user'),
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(max_length=255)),
                ('uID_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1_relationships', to='MyDiscord.user')),
                ('uID_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2_relationships', to='MyDiscord.user')),
            ],
            options={
                'unique_together': {('uID_1', 'uID_2')},
            },
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_uID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='MyDiscord.user')),
                ('sender_uID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='MyDiscord.user')),
            ],
            options={
                'unique_together': {('sender_uID', 'receiver_uID')},
            },
        ),
    ]
