# Generated by Django 5.0.6 on 2024-05-15 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyDiscord', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('receiver_uID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='MyDiscord.user')),
                ('sender_uID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='MyDiscord.user')),
            ],
            options={
                'unique_together': {('sender_uID', 'receiver_uID')},
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(max_length=255)),
                ('uID_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1_relationships', to='MyDiscord.user')),
                ('uID_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2_relationships', to='MyDiscord.user')),
            ],
            options={
                'unique_together': {('uID_1', 'uID_2')},
            },
        ),
    ]
