# Generated by Django 5.0.6 on 2024-05-15 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyDiscord', '0002_friendrequest_relationship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='status',
        ),
    ]
