# Generated by Django 4.1 on 2024-05-11 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyDiscord', '0003_rename_thread_message_thread_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='thread_id',
            new_name='thread',
        ),
    ]
