# Generated by Django 4.1 on 2024-05-11 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyDiscord', '0005_alter_message_thread'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='author',
            new_name='author_id',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='thread',
            new_name='thread_id',
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='initial_message',
            new_name='initial_message_id',
        ),
    ]
