# Generated by Django 4.1 on 2024-05-11 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyDiscord', '0007_alter_message_author_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='author_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='thread_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='initial_message_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
