# Generated by Django 4.1 on 2024-05-15 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyDiscord', '0008_alter_message_author_id_alter_message_thread_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='MyDiscord.user'),
        ),
        migrations.AlterField(
            model_name='message',
            name='thread_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='MyDiscord.thread'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='initial_message_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiating_thread', to='MyDiscord.message'),
        ),
    ]
