# Generated by Django 4.1 on 2024-05-15 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyDiscord', '0002_friendrequest_relationship'),
        ('MyDiscord', '0009_alter_message_author_id_alter_message_thread_id_and_more'),
    ]

    operations = [
    ]
