# Generated by Django 4.1 on 2024-05-15 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyDiscord', '0010_merge_20240515_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_author', to='MyDiscord.user'),
        ),
        migrations.AlterField(
            model_name='message',
            name='thread_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_of_thread', to='MyDiscord.thread'),
        ),
    ]
