# Generated by Django 4.1 on 2024-05-15 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyDiscord', '0013_alter_message_thread_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='thread_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_of_thread', to='MyDiscord.thread'),
        ),
    ]
