# Generated by Django 4.1 on 2024-05-15 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyDiscord', '0015_alter_message_author_id_alter_message_thread_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='thread_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
