# Generated by Django 4.1 on 2024-05-16 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyDiscord', '0018_alter_message_latitude_alter_message_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='thread_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
