# Generated by Django 4.1 on 2024-05-16 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyDiscord', '0019_alter_thread_thread_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('recipient_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
                ('message_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyDiscord.message')),
                ('uID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyDiscord.user')),
            ],
        ),
    ]
